name: molten_navigationbar_flutter
description: An animated bottom navigation bar with many parameters to tweak.
version: 0.0.1
author: Ayman Alzahrani <aymanz.dev@gmail.com> Majed Alhasen <sidrozz@gmail.com> 
homepage: https://github.com/AymanProjects/Molten_BottomNavBar_Flutter

environment:
  sdk: ">=2.3.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: